# Generated by Django 3.2.7 on 2021-09-10 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='категория статьи')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'категория статьи',
                'verbose_name_plural': 'категории статьи',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='тег')),
                ('slug', models.SlugField(max_length=64, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок статьи')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('content', models.TextField(max_length=10000, verbose_name='текст статьи')),
                ('created_at', models.DateField(auto_now=True, verbose_name='дата создания')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=32)),
                ('categories', models.ManyToManyField(related_name='category_posts', to='blog.Category', verbose_name='категория статьи')),
                ('tags', models.ManyToManyField(blank=True, related_name='tag_posts', to='blog.Tag', verbose_name='тег статьи')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='текст комментариия')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('active', models.BooleanField(default=False, verbose_name='активный')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post', verbose_name='пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
